### ISSUE TITLE
请问数据库中user表内enable，switch，type，各是用来实现怎样的功能

### ISSUE THREAD

**Issue by coachpo** [Mujj/shadowsocks#3]
我测试了下enable，switch改为0，后端便不开启该用户的服务，不知道type是用来干什么的。求告知

**Comment by coachpo** [comment]
创建表的文件是这个shadowsocks/shadowsocks.sql

**Comment by Mujj** [comment]
enable 是账户是否启用的意思，你改为0以后服务端会自动删除端口，switch暂时不知道，type也暂时不明。

**Comment by coachpo** [comment]
根据我的测试。enable或者switch改为0之后服务端程序启动时不会开启这个用户的服务，个人推测应该是用来控制用户访问的，但是测试中发现不能实现动态停止的功能。

**Comment by Mujj** [comment]
动态停止是可以的，我测试过，改为0以后是马上就停止。
