### ISSUE TITLE
监听ipv6出现问题，即使绑定服务器ipv6地址也不行

### ISSUE THREAD

**Issue by rqd1995** [Mujj/shadowsocks#4]
[Errno -2] Name or service not known
错误内容如上，即使按照之前的issue绑定ipv6地址也不行，还是报同样的错误，ipv4可正常使用。

**Comment by Mujj** [comment]
我这个只是一个自用的后端，免得每次都从别人那里取，前面有遇到过这样的问题，绑定就好了。

**Comment by rqd1995** [comment]
绑定就是在config.json里面把[::]替换为[xxxxxxxxxxxxx]的ip地址吗？我这样做了可是不行啊

**Comment by Mujj** [comment]
错了，要去掉[]符号，改成如下面这样
`"server_ipv6": "2605:f700:40:400::13c6:54b1",`

**Comment by rqd1995** [comment]
非常感谢，服务器跑起来了
